services:
  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "warehouse-db"
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'